"""secretCode

Revision ID: 4ef125e3ed67
Revises: 55d33abbd5ba
Create Date: 2018-12-09 19:07:19.964876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ef125e3ed67'
down_revision = '55d33abbd5ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('secretCode', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'secretCode')
    # ### end Alembic commands ###
