"""hide-post

Revision ID: 55d33abbd5ba
Revises: b291d7bf99a7
Create Date: 2018-11-25 22:49:45.228020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55d33abbd5ba'
down_revision = 'b291d7bf99a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('hide', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'hide')
    # ### end Alembic commands ###
