"""empty message

Revision ID: 5fc38d8fcfbc
Revises: 76f13dd6075f
Create Date: 2019-01-05 20:05:29.895628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fc38d8fcfbc'
down_revision = '76f13dd6075f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id_string', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_users_id_string'), 'users', ['id_string'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id_string'), table_name='users')
    op.drop_column('users', 'id_string')
    # ### end Alembic commands ###
