"""comment

Revision ID: b291d7bf99a7
Revises: c7863ac28cd3
Create Date: 2018-11-17 00:12:06.755706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b291d7bf99a7'
down_revision = 'c7863ac28cd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('response_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'comments', ['response_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'response_id')
    # ### end Alembic commands ###
